# Generated by Django 3.2.6 on 2021-10-09 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='updateuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='history',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Declined', 'Declined')], default='Successful', max_length=20),
        ),
        migrations.AddField(
            model_name='history',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updateuser',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='PendingTransfer',
        ),
    ]
