# Generated by Django 3.2.6 on 2021-10-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211009_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='valid_ID_backview',
        ),
        migrations.RemoveField(
            model_name='updateuser',
            name='valid_ID_frontview',
        ),
    ]
